version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps): "

  - package-ecosystem: "nuget"
    directories:
      - "/" # Also discovers /.config directory
      - "/src"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      
