changelog:
  # Global exclude (no need to re-exclude in the categories section)
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
      - github-actions

  categories:
    - title: ✨ Enhancements
      labels:
        - enhancement
    - title: 🐛 Bug fixes
      labels:
        - bug
    - title: 🧹 Housekeeping
      labels:
        - '*'