name: "Runner setup"
description: "Sets up the runner with basic prerequisites"
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DOTNET_NOLOGO=false" >> $GITHUB_ENV
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
        echo "NUKE_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV

    - name: Set up .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        global-json-file: global.json

    - name: Restore .NET tools
      shell: bash
      run: dotnet tool restore

    - name: Install Containerlab
      if: runner.os == 'Linux'
      shell: bash
      run: bash -c "$(curl -sL https://get.containerlab.dev)"
