<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agent.Host\Agent.Host.csproj" />
     <ProjectReference Include="..\Coordinator.Client\Coordinator.Client.csproj" />
    <ProjectReference Include="..\Coordinator.Host\Coordinator.Host.csproj" />
    <ProjectReference Include="..\Coordinator.Services\Coordinator.Services.csproj" />
    <ProjectReference Include="..\TestUtilities\TestUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.NUnit" />
  </ItemGroup>

</Project>
