name: 🔁 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      verbosity:
        description: 'MSBuild verbosity level'
        required: false
        default: 'normal'
        type: choice
        options:
          - 'quiet'
          - 'minimal'
          - 'normal'
          - 'detailed'
          - 'diagnostic'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      # https://docs.github.com/en/actions/how-tos/monitor-workflows/enable-debug-logging
      ACTIONS_RUNNER_DEBUG: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up runner
        uses: ./.github/actions/setup-runner

      - name: Run tests
        run: |
          dotnet run \
          --project ./build/_build.csproj \
          --target Test \
          --commit ${{ github.sha }} \
          --msbuildverbosity ${{ github.event.inputs.verbosity }}

      - name: Display test results
        continue-on-error: true
        if: always()
        run: dotnet trx --verbosity normal

      - name: Check for warnings
        continue-on-error: true # TODO remove
        run: |
          dotnet run \
          --project ./build/_build.csproj \
          --target CheckWarnings