name: ⛴️ Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Pre-release"
        type: boolean
        default: true
      prereleaseidentifiers:
        description: "Dot-separated pre-release identifiers e.g. 'attempt.42'"
        required: false
        type: string

jobs:
  version:
    name: 🔢 Version
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 2
    outputs:
      value: ${{ steps.output-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up runner
        uses: ./.github/actions/setup-runner

      - name: Output version
        id: output-version
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target OutputVersion
          --configuration Release
          --githubtoken ${{ secrets.GITHUB_TOKEN }}
          --releasetype ${{ inputs.prerelease && 'PreRelease' || 'Release' }}
          ${{ inputs.prereleaseidentifiers != '' && format('--prereleaseidentifiers {0}', inputs.prereleaseidentifiers) || '' }}

  build-linux:
    name: 🐧 Build
    runs-on: ubuntu-latest
    needs: [ version ]
    permissions:
      contents: read
    timeout-minutes: 10
    outputs:
      container-image-ref: ${{ steps.push-container.outputs.container-image-ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up runner
        uses: ./.github/actions/setup-runner

      - name: Create artifacts
        id: push-container
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target CreateLinuxArtifacts
          --commit ${{ github.sha }}
          --platform linux_x64
          --configuration Release
          --githubtoken ${{ secrets.GITHUB_TOKEN }}
          --dockerhubpassword ${{ secrets.DOCKER_HUB_PAT_RW }}
          --releasetype ${{ inputs.prerelease && 'PreRelease' || 'Release' }}
          --exactversion ${{ needs.version.outputs.value }}

      - name: Display test results
        continue-on-error: true
        if: always()
        run: dotnet trx --verbosity normal

      - name: Check for warnings
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target CheckBuildWarnings

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux
          path: artifacts/
          if-no-files-found: error

  build-windows:
    name: 🪟 Build
    runs-on: windows-latest
    needs: [ version ]
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up runner
        uses: ./.github/actions/setup-runner

      - name: Create artifacts
        shell: bash
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target CreateWindowsArtifacts
          --commit ${{ github.sha }}
          --platform win_x64
          --configuration Release
          --githubtoken ${{ secrets.GITHUB_TOKEN }}
          --releasetype ${{ inputs.prerelease && 'PreRelease' || 'Release' }}
          --exactversion ${{ needs.version.outputs.value }}

      - name: Display test results
        continue-on-error: true
        if: always()
        run: dotnet trx --verbosity normal

      - name: Check for warnings
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target CheckBuildWarnings

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-windows
          path: artifacts/
          if-no-files-found: error

  release:
    name: ⛴️ Release
    runs-on: ubuntu-latest
    needs: [ version, build-linux, build-windows ]
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up runner
        uses: ./.github/actions/setup-runner

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-linux
          path: artifacts/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts-windows
          path: artifacts/

      - name: Release
        run: >
          dotnet run
          --project ./build/_build.csproj
          --target ${{ inputs.prerelease && 'CreatePreRelease' || 'CreateRelease' }}
          --commit ${{ github.sha }}
          --configuration Release
          --githubtoken ${{ secrets.GITHUB_TOKEN }}
          --dockerhubpassword ${{ secrets.DOCKER_HUB_PAT_RWD }}
          --containerimageref ${{ needs.build-linux.outputs.container-image-ref }}
          --releasetype ${{ inputs.prerelease && 'PreRelease' || 'Release' }}
          --exactversion ${{ needs.version.outputs.value }}
